In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3, 4, 5]
type(my_list) 

list

In [4]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [5]:
my_numpy_array = np.array(my_list)
type(my_numpy_array)

numpy.ndarray

In [6]:
my_numpy_array.max()

np.int64(5)

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.random.random(5)

array([0.17627324, 0.71897123, 0.915389  , 0.01687193, 0.96548596])

In [10]:
my_list1 = [1, 2]
my_list2 = [2, 3]
my_list1 + my_list2

[1, 2, 2, 3]

In [11]:
my_numpy_array1 = np.array(my_list1)
my_numpy_array2 = np.array(my_list2)
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [12]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [13]:
other_array = np.array([1, 2, 3, 4, 5])
other_array.min()

np.int64(1)

In [14]:
other_array.sum()

np.int64(15)

In [15]:
list(range(1, 10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np_array = np.arange(0,10)
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np_array[0]

np.int64(0)

In [20]:
np_array[-1]

np.int64(9)

In [21]:
np_array[1:4:]

array([1, 2, 3])

In [22]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
np_array[2:6:2]

array([2, 4])

In [24]:
np.random.randn(5)

array([-2.41615991, -1.14148346, -1.00338107,  0.54641404,  0.27288572])

In [25]:
np.random.randn(5,5)

array([[ 0.01568185, -0.13289814,  0.8282783 ,  0.60408172, -1.55317673],
       [-0.29960675, -0.5771124 ,  1.10531867, -0.14911405, -0.40449917],
       [-0.66428039,  1.02064571, -0.56232678, -0.69191147,  1.26412077],
       [-0.30287939, -0.32716281,  0.81969164, -1.30981539, -0.13949876],
       [ 1.02686024, -0.95899451,  0.79462769, -0.43614221, -1.64310758]])

In [27]:
np.random.randint(1,300,5)

array([222,  31, 135, 133,  94], dtype=int32)