In [6]:
%pip install torch torchvision

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
    --------------------------------------- 1.6/114.6 MB 10.0 MB/s eta 0:00:12
   - -------------------------------------- 3.7/114.6 MB 9.5 MB/s eta 0:00:12
   -- ------------------------------------- 5.8/114.6 MB 10.1 MB/s eta 0:00:11
   -- ------------------------------------- 7.9/114.6 MB 10.2 MB/s eta 0:00:11
   --- ------------------------------------ 10.0/114.6 MB 10.4 MB/s eta 0:00:11
   ---- ----------------------------------- 11.8/114.6 MB 10.1 MB/s eta 0:00:11
   ---- ----------------------------------- 13.6/114.6 MB 9.9 MB/s eta 0:00:11
   ----- ---------------------------------- 15.7/114.6 MB 10.0 MB/s eta 0:00:10
   ------ --------------------------------- 18.1/114.6 MB 10.0 MB/s eta 0:00:10
   ------ --------------------------------- 19.7/114.6 MB 9.8 MB/s eta 0:00:10
   ------- -------------------------------- 21.8/114.6 MB 

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [7]:
import torch
import numpy as np

In [8]:
torch.tensor(10)

tensor(10)

In [9]:
torch.tensor([10, 20])

tensor([10, 20])

In [10]:
scalar = torch.tensor(7)

In [11]:
type(scalar)

torch.Tensor

In [12]:
scalar + 5

tensor(12)

In [13]:
scalar - 2

tensor(5)

In [14]:
scalar * 4

tensor(28)

In [15]:
scalar / 2

tensor(3.5000)

In [16]:
scalar.dim()

0

In [17]:
scalar.shape

torch.Size([])

In [19]:
scalar.item()

7

In [20]:
numpy_int = np.int32(10)

In [21]:
numpy_int

np.int32(10)

In [22]:
numpy_int + 5

np.int32(15)

In [23]:
numpy_int - 2

np.int32(8)

In [24]:
numpy_int * 4

np.int32(40)

In [25]:
numpy_int / 3

np.float64(3.3333333333333335)

In [28]:
scalar_from_np = torch.tensor(numpy_int)

In [29]:
scalar_from_np

tensor(10, dtype=torch.int32)

In [31]:
scalar.dtype

torch.int64

In [32]:
new_scalar = torch.tensor(25, dtype=torch.int32)
new_scalar

tensor(25, dtype=torch.int32)

In [33]:
tensor_float = torch.tensor(3.14)
tensor_float

tensor(3.1400)

In [34]:
vector = torch.tensor([1, 2, 3])

In [35]:
vector.dim()

1

In [36]:
vector.shape

torch.Size([3])

In [37]:
vector = torch.tensor([1, 2, 3, 5])

In [38]:
vector.dim()

1

In [39]:
vector.shape

torch.Size([4])

In [40]:
matrix = torch.tensor([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [41]:
matrix.dim()

2

In [42]:
matrix.shape

torch.Size([3, 3])

In [43]:
tensor_example = torch.tensor([[[[1, 2, 3],
                                [4, 5, 6],
                                [7, 8, 9]]]])

In [44]:
tensor_example

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [45]:
tensor_example.dim()

4

In [46]:
tensor_example.shape

torch.Size([1, 1, 3, 3])

In [47]:
float_32_tensor = torch.tensor([3.14], dtype=torch.float32, device = None, requires_grad = False)

In [48]:
float_32_tensor

tensor([3.1400])