In [1]:
import torch
import numpy as np

In [2]:
random_array = np.random.randn(3, 5)

In [3]:
random_array

array([[-0.78484662, -0.73694521, -0.62434927,  0.19653254, -1.40792843],
       [ 0.88102828,  0.40191223,  0.34572934,  0.44653479,  1.24526121],
       [ 0.31906746, -0.30322284,  0.78256832, -1.68548235, -0.26306502]])

In [4]:
type(random_array)

numpy.ndarray

In [5]:
random_array.shape

(3, 5)

In [6]:
random_array.ndim

2

In [7]:
random_matrix = torch.rand(size=(3, 5))

In [8]:
random_matrix

tensor([[0.8868, 0.0193, 0.7325, 0.5506, 0.9020],
        [0.5805, 0.7302, 0.1108, 0.6810, 0.2906],
        [0.4080, 0.4161, 0.8342, 0.4959, 0.1946]])

In [10]:
random_matrix.ndim

2

In [11]:
random_matrix.shape

torch.Size([3, 5])

In [12]:
random_matrix.dtype

torch.float32

In [13]:
random_image_tensor = torch.rand(size=(224, 224, 3))

In [14]:
random_image_tensor

tensor([[[9.9209e-01, 6.2081e-01, 7.8521e-01],
         [2.5810e-01, 5.5498e-01, 8.6868e-01],
         [1.0944e-01, 1.1984e-01, 7.0666e-01],
         ...,
         [4.4193e-01, 6.8637e-01, 3.8351e-01],
         [1.0878e-01, 9.0432e-02, 9.5756e-01],
         [7.2368e-01, 3.5963e-01, 6.4108e-01]],

        [[7.7283e-01, 3.9820e-01, 4.0329e-01],
         [4.6880e-01, 3.3985e-01, 9.5267e-01],
         [4.2847e-01, 2.7851e-01, 2.5515e-01],
         ...,
         [6.4360e-02, 5.6698e-01, 7.3739e-01],
         [8.7198e-01, 4.7002e-01, 2.7106e-01],
         [7.3687e-01, 5.7377e-01, 1.0832e-01]],

        [[6.3988e-01, 2.8705e-01, 6.3053e-01],
         [3.8831e-01, 1.3798e-04, 6.3602e-01],
         [5.4215e-01, 2.5995e-01, 2.0494e-01],
         ...,
         [7.5018e-02, 2.7277e-01, 8.9939e-01],
         [8.7854e-01, 7.1321e-02, 8.0671e-01],
         [6.3456e-01, 7.1715e-02, 8.5009e-02]],

        ...,

        [[6.2072e-01, 3.1804e-01, 6.7111e-01],
         [9.5325e-01, 3.6155e-01, 7.0188e-01]