In [2]:
import torch
import numpy as np

In [3]:
tensor = torch.tensor(data=[1, 2, 3])

In [4]:
tensor * tensor

tensor([1, 4, 9])

In [5]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

In [6]:
matrix * matrix

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [7]:
matrix @ matrix

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [8]:
torch.matmul(matrix, matrix)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [9]:
matrix.shape

torch.Size([3, 3])

In [10]:
tensor1 = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

In [11]:
tensor2 = torch.tensor([[7, 8],
                        [9, 10],
                        [11, 12]])

In [12]:
tensor1.shape

torch.Size([3, 2])

In [13]:
tensor2.shape

torch.Size([3, 2])

In [15]:
tensor1 @ tensor2.T

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [16]:
tensor2.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [17]:
A = torch.tensor([[1, 2, 3]])

In [18]:
A.shape

torch.Size([1, 3])

In [19]:
A.ndim

2

In [20]:
B = torch.tensor([[4],[5],[6]])

In [21]:
B.shape

torch.Size([3, 1])

In [22]:
B.ndim

2

In [23]:
A @ B

tensor([[32]])