In [1]:
import torch

In [2]:
tensor = torch.arange(0, 50, 5)

In [3]:
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [4]:
tensor.min()

tensor(0)

In [5]:
tensor.max()

tensor(45)

In [6]:
tensor.sum()

tensor(225)

In [7]:
tensor.median()

tensor(20)

In [8]:
tensor.dtype

torch.int64

In [9]:
tensor = tensor.type(torch.float)

In [10]:
tensor.mean()

tensor(22.5000)

In [11]:
tensor.argmax()

tensor(9)

In [12]:
tensor[9]

tensor(45.)

In [13]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

In [14]:
matrix.shape

torch.Size([2, 3])

In [15]:
matrix.ndim

2

In [16]:
matrix[0][0]

tensor(1)

In [17]:
#manuipulating tensor: reshaping, stacking, squeezing, unsqueezing

In [18]:
x = torch.arange(1,10,1)

In [19]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x.shape

torch.Size([9])

In [21]:
x.ndim

1

In [22]:
x_reshaped = x.reshape(1,9)

In [23]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [24]:
x_reshaped.shape

torch.Size([1, 9])

In [25]:
x_reshaped.ndim

2

In [29]:
y = torch.randn(224, 224, 3)

In [30]:
y.shape

torch.Size([224, 224, 3])

In [31]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [33]:
x_reshaped = x.reshape(3,3)

In [34]:
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [35]:
x_reshaped = x.reshape(9,1)

In [36]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [38]:
x_reshaped[0] = 20

In [39]:
x_reshaped

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [40]:
x

tensor([20,  2,  3,  4,  5,  6,  7,  8,  9])

In [41]:
x_view = x.view(9,1)

In [42]:
x_view

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [43]:
x_view[0] = 10

In [44]:
x_view

tensor([[10],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [45]:
x

tensor([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [46]:
# view -> contigious tensor

In [47]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

In [48]:
x.is_contiguous()

True

In [49]:
y = x.t()

In [50]:
y

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [51]:
y.is_contiguous()

False

In [52]:
x.view(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [53]:
# y.view(1,6) hata verir çünkü contigious değil

In [54]:
y.reshape(1,6)

tensor([[1, 4, 2, 5, 3, 6]])

In [55]:
#stacking

In [56]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [57]:
torch.stack([x,x,x,x], dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [58]:
torch.stack([x,x,x,x], dim=1)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]])

In [59]:
# squeeze & unsqueeze

In [60]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [61]:
x.shape

torch.Size([2, 3])

In [62]:
x.ndim

2

In [64]:
x.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [65]:
x.squeeze().shape

torch.Size([2, 3])

In [66]:
x.squeeze().ndim

2

In [67]:
x = torch.tensor([[1,2,3]])

In [68]:
x.shape

torch.Size([1, 3])

In [69]:
x.ndim

2

In [70]:
x.squeeze()

tensor([1, 2, 3])

In [71]:
x.squeeze().shape

torch.Size([3])

In [72]:
x.squeeze().ndim

1

In [73]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

In [74]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [75]:
x.unsqueeze(dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [76]:
y = x.unsqueeze(dim=0)

In [77]:
y

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [78]:
y.shape

torch.Size([1, 2, 3])

In [79]:
y.ndim

3

In [80]:
z = y.unsqueeze(dim=0)

In [81]:
z

tensor([[[[1, 2, 3],
          [4, 5, 6]]]])

In [82]:
z.shape

torch.Size([1, 1, 2, 3])

In [83]:
z.ndim

4

In [84]:
t = z.squeeze()

In [85]:
t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [86]:
t.ndim

2

In [87]:
t.shape

torch.Size([2, 3])

In [88]:
#permute 

In [89]:
x = torch.rand(size=(224, 224, 3))

In [90]:
x.shape

torch.Size([224, 224, 3])

In [91]:
x_permuted = x.permute(2, 0, 1) # axis 0 -> 1, axis 1 -> 2, axis 2 -> 0

In [92]:
x_permuted.shape

torch.Size([3, 224, 224])

In [93]:
# indexing & slicing

In [94]:
a = torch.arange(1, 10,1)

In [95]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
a = a.reshape(1,3,3)

In [99]:
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [100]:
a[0][0][0]

tensor(1)

In [101]:
a.shape

torch.Size([1, 3, 3])

In [102]:
a.ndim

3

In [103]:
a[:, 0, 0]

tensor([1])

In [104]:
a[:,1,0]

tensor([4])

In [105]:
a[:, :, 0]

tensor([[1, 4, 7]])

In [106]:
a[:, 0, :]

tensor([[1, 2, 3]])

In [107]:
# random seed

In [110]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])