In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [4]:
device

'cuda'

In [5]:
tensor = torch.tensor([1, 2, 3])

In [6]:
tensor

tensor([1, 2, 3])

In [7]:
tensor.device

device(type='cpu')

In [8]:
# manuelly set the device

In [9]:
tensor_on_gpu = tensor.to(device)

In [10]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [11]:
tensor.numpy()

array([1, 2, 3])

In [13]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])

In [14]:
# context manager

In [16]:
with torch.device(device):
    tensor2 = torch.tensor([1, 2, 3])
    layer = torch.nn.Linear(20,30)

In [17]:
tensor2.device

device(type='cuda', index=0)

In [18]:
layer.weight.device

device(type='cuda', index=0)

In [19]:
# torch.set_default_device

In [20]:
device

'cuda'

In [21]:
torch.set_default_device(device)

In [22]:
tensor4 = torch.tensor([1, 2, 3])
layer2 = torch.nn.Linear(10, 20)

In [23]:
tensor4.device

device(type='cuda', index=0)

In [24]:
layer2.weight.device

device(type='cuda', index=0)

In [27]:
tensor2.device

device(type='cuda', index=0)