In [1]:
import numpy as np

In [2]:
my_matrix = [[5,10],[15,20]]

In [3]:
my_matrix[0]

[5, 10]

In [4]:
my_matrix[1]

[15, 20]

In [5]:
my_matrix[0][1]

10

In [6]:
numpy_matrix = np.array([[5,10],[15,20]])
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [7]:
numpy_matrix[1][0]

np.int64(15)

In [8]:
numpy_matrix.sum()

np.int64(50)

In [9]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.random.random((2, 3))

array([[0.67117204, 0.32073854, 0.71699585],
       [0.49482893, 0.78398372, 0.19995188]])

In [12]:
first_array = np.array([[10,20],[30,40]])
second_array = np.array([[5,15],[25,35]])
first_array + second_array

array([[15, 35],
       [55, 75]])

In [14]:
third_array = np.array([[50,60]])
third_array

array([[50, 60]])

In [15]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [16]:
first_array * 2

array([[20, 40],
       [60, 80]])

In [17]:
first_array / 4

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [19]:
third_array = np.array([[10],[20]])
third_array

array([[10],
       [20]])

In [20]:
third_array.shape

(2, 1)

In [21]:
first_array

array([[10, 20],
       [30, 40]])

In [22]:
second_array

array([[ 5, 15],
       [25, 35]])

In [23]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [24]:
first_matrix = np.array([[10,20,30]])
first_matrix

array([[10, 20, 30]])

In [25]:
first_matrix.shape

(1, 3)

In [27]:
second_matrix = np.array([[2,3],[2,3],[2,3]])
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [28]:
second_matrix.shape

(3, 2)

In [30]:
result_matrix =first_matrix.dot(second_matrix)

In [31]:
result_matrix

array([[120, 180]])

In [32]:
result_matrix.shape

(1, 2)