In [1]:
import numpy as np

In [2]:
new_array = np.random.randint(1,100,20)
new_array

array([82, 23, 41, 74, 94, 65, 99, 30, 97, 88, 61, 91, 59, 82, 66, 94, 92,
       61, 90, 56], dtype=int32)

In [3]:
new_array > 25

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [4]:
new_array[new_array > 25]

array([82, 41, 74, 94, 65, 99, 30, 97, 88, 61, 91, 59, 82, 66, 94, 92, 61,
       90, 56], dtype=int32)

In [5]:
new_array[new_array < 25]

array([23], dtype=int32)

In [6]:
matrix_array = np.array([[10,20],[20,30],[30,40]])
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [7]:
matrix_array.shape

(3, 2)

In [8]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [9]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [10]:
random_array = np.random.random((6,1))
random_array

array([[0.53297489],
       [0.32584018],
       [0.2574196 ],
       [0.10024361],
       [0.21303389],
       [0.8411104 ]])

In [11]:
random_array.shape

(6, 1)

In [12]:
random_array.reshape(2,3)

array([[0.53297489, 0.32584018, 0.2574196 ],
       [0.10024361, 0.21303389, 0.8411104 ]])

In [13]:
data = np.array([10,12,13,15,18,25,100,105])
mean = np.mean(data)

In [14]:
mean

np.float64(37.25)

In [15]:
std = np.std(data)
std

np.float64(37.9333296719389)

In [16]:
z_score = (data - mean) / std
z_score

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [17]:
data[z_score > 0]

array([100, 105])

In [18]:
A = np.array([[1,2],[3,4]])
B = np.array([8,19])
solution = np.linalg.solve(A,B)
solution

array([3. , 2.5])